### ISSUE TITLE
1.0 roadmap

### ISSUE THREAD

**Issue by chfast** [holiman/uint256#50]
1. [x] Full test coverage: https://codecov.io/gh/holiman/uint256
2. [x] Inspect `Exp()` implementation (constant time, but gas cost proportional to exponent size).
3. [x] Remove unneeded public functions.
4. [x] Fix `SDiv()`, `SMod()` - they modify arguments.
5. [x] Review decision to return zero on division by zero. #62 #64
6. [x] ~~Test arm architecture?~~
7. [x] ~~Test any big-endian architecture?~~ #60
8. [x] Unify names: `Sub64()` vs `LtUint64()`. #65
9. [x] Run benchmarks against 0.1 version.

**Comment by chfast** [comment]
Comparison with `v0.1.0`:
```
name                      old time/op  new time/op  delta
_Add/single/uint256-6     2.00ns ± 0%  2.00ns ± 0%     ~     (all equal)
_Sub/single/uint256-6     2.00ns ± 0%  2.00ns ± 0%     ~     (all equal)
_Sub/single/uint256_of-6  2.00ns ± 0%  2.00ns ± 0%     ~     (all equal)
Mul/single/uint256-6      15.0ns ± 0%   8.7ns ± 0%  -41.75%  (p=0.000 n=10+10)
Square/single/uint256-6   16.1ns ± 0%   6.3ns ± 0%  -60.68%  (p=0.000 n=10+10)
_And/single/uint256-6     1.77ns ± 1%  1.76ns ± 1%     ~     (p=0.070 n=10+10)
_Or/single/uint256-6      1.77ns ± 0%  1.77ns ± 0%     ~     (all equal)
_Xor/single/uint256-6     1.77ns ± 0%  1.77ns ± 1%     ~     (p=0.353 n=7+10)
_Cmp/single/uint256-6     2.83ns ± 0%  2.83ns ± 0%     ~     (all equal)
Lt/large/uint256-6        2.78ns ± 0%  2.78ns ± 0%     ~     (p=1.000 n=10+10)
Lt/small/uint256-6        2.78ns ± 0%  2.78ns ± 0%     ~     (all equal)
_Lsh/n_eq_0/uint256-6     4.50ns ± 0%  4.50ns ± 0%     ~     (all equal)
_Lsh/n_gt_192/uint256-6   4.75ns ± 0%  4.75ns ± 0%     ~     (all equal)
_Lsh/n_gt_128/uint256-6   6.10ns ± 0%  6.10ns ± 0%     ~     (all equal)
_Lsh/n_gt_64/uint256-6    8.07ns ± 0%  8.07ns ± 0%     ~     (p=1.296 n=10+8)
_Lsh/n_gt_0/uint256-6     8.97ns ± 0%  8.97ns ± 0%     ~     (p=0.173 n=10+9)
_Rsh/n_eq_0/uint256-6     4.50ns ± 0%  4.50ns ± 0%     ~     (all equal)
_Rsh/n_gt_192/uint256-6   4.75ns ± 0%  4.75ns ± 0%     ~     (all equal)
_Rsh/n_gt_128/uint256-6   6.06ns ± 0%  6.07ns ± 0%   +0.11%  (p=0.041 n=8+9)
_Rsh/n_gt_64/uint256-6    8.01ns ± 0%  8.01ns ± 0%     ~     (all equal)
_Rsh/n_gt_0/uint256-6     9.15ns ± 0%  9.15ns ± 0%     ~     (p=0.650 n=10+10)
_Exp/large/uint256-6      6.60µs ± 0%  3.29µs ± 0%  -50.17%  (p=0.000 n=10+9)
_Exp/small/uint256-6       568ns ± 0%   278ns ± 0%  -51.01%  (p=0.000 n=10+10)
Div/small/uint256-6       12.5ns ± 0%  11.6ns ± 1%   -7.00%  (p=0.000 n=10+8)
Div/mod64/uint256-6       62.7ns ± 0%  62.7ns ± 0%   -0.05%  (p=0.000 n=10+9)
Div/mod128/uint256-6      98.3ns ± 0%  98.0ns ± 0%   -0.25%  (p=0.000 n=10+9)
Div/mod192/uint256-6      88.1ns ± 0%  88.1ns ± 0%     ~     (p=0.165 n=8+9)
Div/mod256/uint256-6      74.0ns ± 0%  74.6ns ± 0%   +0.78%  (p=0.000 n=10+9)
Mod/small/uint256-6       14.1ns ± 0%  13.9ns ± 0%   -1.14%  (p=0.000 n=10+10)
Mod/mod64/uint256-6       65.0ns ± 0%  65.0ns ± 0%     ~     (p=0.180 n=9+10)
Mod/mod128/uint256-6       100ns ± 0%   101ns ± 0%   +0.50%  (p=0.033 n=10+10)
Mod/mod192/uint256-6      90.3ns ± 0%  90.7ns ± 0%   +0.48%  (p=0.000 n=9+8)
Mod/mod256/uint256-6      76.4ns ± 0%  77.4ns ± 1%   +1.30%  (p=0.000 n=8+10)
AddMod/small/uint256-6    18.3ns ± 0%  18.3ns ± 0%     ~     (all equal)
AddMod/mod64/uint256-6    73.5ns ± 0%  73.5ns ± 0%     ~     (p=0.108 n=10+9)
AddMod/mod128/uint256-6    117ns ± 0%   117ns ± 0%     ~     (all equal)
AddMod/mod192/uint256-6    109ns ± 0%   109ns ± 0%     ~     (all equal)
AddMod/mod256/uint256-6   95.6ns ± 0%  95.6ns ± 0%     ~     (p=0.126 n=10+8)
MulMod/small/uint256-6    41.1ns ± 0%  37.3ns ± 0%   -9.25%  (p=0.000 n=10+8)
MulMod/mod64/uint256-6     111ns ± 0%   107ns ± 0%   -3.60%  (p=0.000 n=9+10)
MulMod/mod128/uint256-6    194ns ± 0%   188ns ± 0%   -3.09%  (p=0.000 n=9+10)
MulMod/mod192/uint256-6    193ns ± 0%   185ns ± 0%   -4.29%  (p=0.000 n=10+10)
MulMod/mod256/uint256-6    185ns ± 0%   180ns ± 0%   -2.49%  (p=0.000 n=10+8)
_SDiv/large/uint256-6     98.0ns ± 0%  99.2ns ± 0%   +1.31%  (p=0.000 n=10+10)
```

The small regression in `SDiv()` is plausible as I remember changing some related code, but I don't think it is big enough to investigate more at the moment.

**Comment by chfast** [comment]
Confirmation that all operations are alloc-free.
```
go test -run=- -bench='.*/.*/uint256' -count=1 -benchmem
goos: linux
goarch: amd64
pkg: github.com/holiman/uint256
Benchmark_Add/single/uint256-8         	642963136	         1.83 ns/op	       0 B/op	       0 allocs/op
Benchmark_Sub/single/uint256-8         	659493867	         1.82 ns/op	       0 B/op	       0 allocs/op
Benchmark_Sub/single/uint256_of-8      	659703169	         1.82 ns/op	       0 B/op	       0 allocs/op
BenchmarkMul/single/uint256-8          	150596756	         7.94 ns/op	       0 B/op	       0 allocs/op
BenchmarkSquare/single/uint256-8       	208577355	         5.75 ns/op	       0 B/op	       0 allocs/op
Benchmark_And/single/uint256-8         	752403680	         1.60 ns/op	       0 B/op	       0 allocs/op
Benchmark_Or/single/uint256-8          	744340167	         1.60 ns/op	       0 B/op	       0 allocs/op
Benchmark_Xor/single/uint256-8         	744703879	         1.60 ns/op	       0 B/op	       0 allocs/op
Benchmark_Cmp/single/uint256-8         	465805855	         2.57 ns/op	       0 B/op	       0 allocs/op
BenchmarkLt/large/uint256-8            	472760140	         2.54 ns/op	       0 B/op	       0 allocs/op
BenchmarkLt/small/uint256-8            	472893454	         2.54 ns/op	       0 B/op	       0 allocs/op
Benchmark_Lsh/n_eq_0/uint256-8         	293210437	         4.09 ns/op	       0 B/op	       0 allocs/op
Benchmark_Lsh/n_gt_192/uint256-8       	277590660	         4.32 ns/op	       0 B/op	       0 allocs/op
Benchmark_Lsh/n_gt_128/uint256-8       	216228476	         5.55 ns/op	       0 B/op	       0 allocs/op
Benchmark_Lsh/n_gt_64/uint256-8        	163512445	         7.34 ns/op	       0 B/op	       0 allocs/op
Benchmark_Lsh/n_gt_0/uint256-8         	146687355	         8.15 ns/op	       0 B/op	       0 allocs/op
Benchmark_Rsh/n_eq_0/uint256-8         	291836214	         4.09 ns/op	       0 B/op	       0 allocs/op
Benchmark_Rsh/n_gt_192/uint256-8       	277773700	         4.32 ns/op	       0 B/op	       0 allocs/op
Benchmark_Rsh/n_gt_128/uint256-8       	216002178	         5.53 ns/op	       0 B/op	       0 allocs/op
Benchmark_Rsh/n_gt_64/uint256-8        	164856595	         7.28 ns/op	       0 B/op	       0 allocs/op
Benchmark_Rsh/n_gt_0/uint256-8         	144140098	         8.32 ns/op	       0 B/op	       0 allocs/op
Benchmark_Exp/large/uint256-8          	  400852	      2992 ns/op	       0 B/op	       0 allocs/op
Benchmark_Exp/small/uint256-8          	 4739943	       253 ns/op	       0 B/op	       0 allocs/op
BenchmarkDiv/small/uint256-8           	100000000	        10.6 ns/op	       0 B/op	       0 allocs/op
BenchmarkDiv/mod64/uint256-8           	20628578	        57.4 ns/op	       0 B/op	       0 allocs/op
BenchmarkDiv/mod128/uint256-8          	13350484	        89.3 ns/op	       0 B/op	       0 allocs/op
BenchmarkDiv/mod192/uint256-8          	14792720	        80.0 ns/op	       0 B/op	       0 allocs/op
BenchmarkDiv/mod256/uint256-8          	17696786	        67.9 ns/op	       0 B/op	       0 allocs/op
BenchmarkMod/small/uint256-8           	94648546	        12.6 ns/op	       0 B/op	       0 allocs/op
BenchmarkMod/mod64/uint256-8           	20331105	        59.0 ns/op	       0 B/op	       0 allocs/op
BenchmarkMod/mod128/uint256-8          	12945447	        91.8 ns/op	       0 B/op	       0 allocs/op
BenchmarkMod/mod192/uint256-8          	14548752	        82.5 ns/op	       0 B/op	       0 allocs/op
BenchmarkMod/mod256/uint256-8          	16925722	        70.7 ns/op	       0 B/op	       0 allocs/op
BenchmarkAddMod/small/uint256-8        	71660088	        16.6 ns/op	       0 B/op	       0 allocs/op
BenchmarkAddMod/mod64/uint256-8        	17931892	        67.1 ns/op	       0 B/op	       0 allocs/op
BenchmarkAddMod/mod128/uint256-8       	11364363	       106 ns/op	       0 B/op	       0 allocs/op
BenchmarkAddMod/mod192/uint256-8       	12157957	        98.7 ns/op	       0 B/op	       0 allocs/op
BenchmarkAddMod/mod256/uint256-8       	13796355	        87.0 ns/op	       0 B/op	       0 allocs/op
BenchmarkMulMod/small/uint256-8        	34321000	        33.9 ns/op	       0 B/op	       0 allocs/op
BenchmarkMulMod/mod64/uint256-8        	12262107	        97.5 ns/op	       0 B/op	       0 allocs/op
BenchmarkMulMod/mod128/uint256-8       	 6998090	       171 ns/op	       0 B/op	       0 allocs/op
BenchmarkMulMod/mod192/uint256-8       	 7123952	       168 ns/op	       0 B/op	       0 allocs/op
BenchmarkMulMod/mod256/uint256-8       	 7308439	       164 ns/op	       0 B/op	       0 allocs/op
Benchmark_SDiv/large/uint256-8         	13130013	        90.2 ns/op	       0 B/op	       0 allocs/op
PASS
ok  	github.com/holiman/uint256	63.778s
```

**Comment by holiman** [comment]
Nearly there!

**Comment by holiman** [comment]
Re "Unify names: `Sub64()` vs `LtUint64()`", How about `SubU64` and `LtU64` ? I thing `Uint64` is overly long. I'm fine with either `Sub64`/`Lt64` but have a slight preference to having `U` in there.. You?

**Comment by holiman** [comment]
On the other hand, big.Int has `SetUint64()`, `Uint64()`,`IsUint64`, `IsInt64` etc. So maybe we should keep the long name

**Comment by chfast** [comment]
> On the other hand, big.Int has `SetUint64()`, `Uint64()`,`IsUint64`, `IsInt64` etc. So maybe we should keep the long name

I noticed the same and I prefer to use full type names. Can change `Sub64` to `SubUint64` but I can leaving without changing it.

**Comment by holiman** [comment]
Well, then let's use full type names, imo

**Comment by holiman** [comment]
Done, release out, closing this! Thanks a lot!
